# Generated by Django 3.1.4 on 2020-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='code',
            field=models.CharField(choices=[('AW', 'AW'), ('DB', 'DB')], max_length=200, null=True),
        ),
    ]
