# Generated by Django 3.1.4 on 2020-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0003_auto_20201203_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='image_1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='image_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='image_3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='image_4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='video_1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='video_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
