# Generated by Django 3.1.4 on 2020-12-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0005_auto_20201203_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='sub_compoent',
            new_name='sub_component',
        ),
    ]
