# Generated by Django 3.1.4 on 2020-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0006_auto_20201204_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='image_3',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='video_2',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='image_1_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='image_2_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='video_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
