# Generated by Django 3.1.4 on 2020-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0008_auto_20201208_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='coord',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='hist_ref',
            field=models.CharField(choices=[('Hist-001', 'Hist-001'), ('Hist-001', 'Hist-001')], default='Not_Signed', max_length=200),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='inspector',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='is_hist',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not_Signed', max_length=200),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='obcr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
