# Generated by Django 3.1.4 on 2020-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0009_auto_20201209_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='pdf_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='hist_ref',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Hist-001', 'Hist-001'), ('Hist-001', 'Hist-001')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='is_hist',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=200),
        ),
    ]
