# Generated by Django 3.1.4 on 2020-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyapp', '0010_auto_20201209_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='criticality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
